# -*- coding: utf-8 -*-
"""Bản sao của DADN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12xB8i-yZ_F-TD7Pm4rXI73gTvJ-qj6SA
"""

!pip install -q ultralytics datasets fastapi python-multipart uvicorn

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!git clone https://huggingface.co/spaces/KhangTruong/Product-Fault-Detection
# %cd /content/Product-Fault-Detection

import datasets

dataset = datasets.load_dataset("KhangTruong/anomaly-detection")

img = dataset["train"][15]["image"]
img.save('example.png')
img

from predictor import predict_json_from_imagefile, predict_image_from_imagefile
json_res = predict_json_from_imagefile('example.png')

img = predict_image_from_imagefile('example.png')

!nohup python api.py &

!ps aux | grep api.py

# !kill 3869         # Replace <PID> with the actual process ID

"""## Đoạn này có thể bị lỗi, do chương trình chưa khởi động, chạy lại cell này lần nữa là ổn"""

import requests

# Replace with the actual URL if it's different
url = "http://localhost:80/predict-json/"

# Load your image file
files = {'file': open('example.png', 'rb')}

# Send a POST request to the endpoint
response = requests.post(url, files=files)

# Process the response
if response.status_code == 200:
    detections = response.json()
    print(detections)
else:
    print(f"Error: {response.status_code}")